basePath: /api/v1
definitions:
  response.SwaggerDeputy:
    properties:
      code:
        example: 87624
        type: integer
      cpf:
        example: "12365478955"
        type: string
      created_at:
        example: "2022-08-07T15:55:00Z"
        type: string
      electoral_name:
        example: José do Povo
        type: string
      id:
        example: a4b04454-f426-44d2-843e-1331510b19ad
        type: string
      image_url:
        example: https://www.camara.leg.br/internet/deputado/bandep/87624.jpg
        type: string
      name:
        example: José da Silva Santos
        type: string
      party:
        $ref: '#/definitions/response.SwaggerParty'
      party_in_the_proposal:
        $ref: '#/definitions/response.SwaggerParty'
      updated_at:
        example: "2022-08-07T15:55:00Z"
        type: string
    type: object
  response.SwaggerDeputyResource:
    properties:
      code:
        example: 87624
        type: integer
      cpf:
        example: "12365478955"
        type: string
      created_at:
        example: "2022-08-07T15:55:00Z"
        type: string
      electoral_name:
        example: José do Povo
        type: string
      id:
        example: a4b04454-f426-44d2-843e-1331510b19ad
        type: string
      image_url:
        example: https://www.camara.leg.br/internet/deputado/bandep/87624.jpg
        type: string
      name:
        example: José da Silva Santos
        type: string
      party:
        $ref: '#/definitions/response.SwaggerParty'
      updated_at:
        example: "2022-08-07T15:55:00Z"
        type: string
    type: object
  response.SwaggerError:
    properties:
      message:
        example: 'Parâmetro inválido: ID da Proposição'
        type: string
    type: object
  response.SwaggerNews:
    properties:
      content:
        example: Foi sancionado o projeto de lei que altera a Lei n° 11.033 para prorrogar
          o Regime Tributário...
        type: string
      created_at:
        example: "2024-01-05T20:25:19Z"
        type: string
      id:
        example: b27947d6-3224-4479-8da4-7917ae16b34d
        type: string
      title:
        example: Novo projeto de lei impulsiona crescimento do setor portuário até
          2028
        type: string
      type:
        example: Proposição
        type: string
      updated_at:
        example: "2024-01-05T20:25:19Z"
        type: string
    type: object
  response.SwaggerNewsPagination:
    properties:
      data:
        items:
          $ref: '#/definitions/response.SwaggerNews'
        type: array
      itens_per_page:
        example: 15
        type: integer
      page:
        example: 1
        type: integer
      total:
        example: 4562
        type: integer
    type: object
  response.SwaggerNewsletter:
    properties:
      content:
        example: O presidente enviou ao Congresso Nacional um projeto de lei que permite
          a concessão de descontos fiscais...
        type: string
      created_at:
        example: "2023-12-24T19:15:22Z"
        type: string
      id:
        example: 7963a6dd-f0b8-4065-8e56-6d2a79626db7
        type: string
      propositions:
        items:
          $ref: '#/definitions/response.SwaggerNewsletterProposition'
        type: array
      reference_date:
        example: "2023-12-23T16:34:14Z"
        type: string
      title:
        example: Proposta inovadora busca impulsionar o crescimento empresarial
        type: string
      updated_at:
        example: "2023-12-24T19:15:22Z"
        type: string
    type: object
  response.SwaggerNewsletterProposition:
    properties:
      code:
        example: 9465723
        type: integer
      content:
        example: O presente requerimento foi elaborado pelos deputados...
        type: string
      created_at:
        example: "2023-08-09T14:55:00Z"
        type: string
      id:
        example: 9dc67bd9-674f-4e4d-9536-07485335c362
        type: string
      image_url:
        example: https://www.vnc.com.br/news/proposition/image/87624.jpg
        type: string
      original_text_url:
        example: https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=4865485
        type: string
      submitted_at:
        example: "2023-08-09T14:25:00Z"
        type: string
      title:
        example: Requerimento de Votação Nominal-Destaque de Emenda
        type: string
      updated_at:
        example: "2023-08-09T14:55:00Z"
        type: string
    type: object
  response.SwaggerOrganization:
    properties:
      acronym:
        example: OVNC
        type: string
      code:
        example: 73214
        type: integer
      created_at:
        example: "2020-12-13T18:37:00Z"
        type: string
      id:
        example: 9d543e6f-20e3-4895-83e4-26b6a976580e
        type: string
      name:
        example: Organização Você na Câmara
        type: string
      nickname:
        example: VNC
        type: string
      type:
        example: Org da Câmara
        type: string
      updated_at:
        example: "2020-12-13T18:37:00Z"
        type: string
    type: object
  response.SwaggerParty:
    properties:
      acronym:
        example: PVNC
        type: string
      code:
        example: 78965
        type: integer
      created_at:
        example: "2021-05-19T18:10:00Z"
        type: string
      id:
        example: 9bb4028f-6fa8-493a-9fe8-e3bbd341c794
        type: string
      image_url:
        example: https://www.camara.leg.br/internet/Deputado/img/partidos/VNC.gif
        type: string
      name:
        example: Partido Você na Câmara
        type: string
      updated_at:
        example: "2021-05-19T18:10:00Z"
        type: string
    type: object
  response.SwaggerProposition:
    properties:
      code:
        example: 9465723
        type: integer
      content:
        example: O presente requerimento foi elaborado pelos deputados...
        type: string
      created_at:
        example: "2023-08-09T14:55:00Z"
        type: string
      deputies:
        items:
          $ref: '#/definitions/response.SwaggerDeputy'
        type: array
      id:
        example: 9dc67bd9-674f-4e4d-9536-07485335c362
        type: string
      image_url:
        example: https://www.vnc.com.br/news/proposition/image/87624.jpg
        type: string
      newsletter:
        $ref: '#/definitions/response.SwaggerNewsletterProposition'
      organizations:
        items:
          $ref: '#/definitions/response.SwaggerOrganization'
        type: array
      original_text_url:
        example: https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=4865485
        type: string
      submitted_at:
        example: "2023-08-09T14:25:00Z"
        type: string
      title:
        example: Requerimento de Votação Nominal-Destaque de Emenda
        type: string
      updated_at:
        example: "2023-08-09T14:55:00Z"
        type: string
    type: object
  response.SwaggerResources:
    properties:
      deputies:
        items:
          $ref: '#/definitions/response.SwaggerDeputyResource'
        type: array
      organizations:
        items:
          $ref: '#/definitions/response.SwaggerOrganization'
        type: array
      parties:
        items:
          $ref: '#/definitions/response.SwaggerParty'
        type: array
    type: object
info:
  contact: {}
  description: Este repositório é responsável pela leitura dos dados nas bases de
    dados da Plataforma Você na Câmara.
  title: VNC Read API
  version: v1
paths:
  /news:
    get:
      description: Esta requisição é responsável por retornar as matérias mais recentes
        disponíveis na plataforma Você na Câmara.
      operationId: GetNews
      parameters:
      - description: Parte do conteúdo das matérias, no título ou conteúdo.
        in: query
        name: content
        type: string
      - description: ID do deputado que elaborou a proposição.
        in: query
        name: deputyId
        type: string
      - description: ID do partido que elaborou a proposição.
        in: query
        name: partyId
        type: string
      - description: ID da organização que elaborou a proposição.
        in: query
        name: organizationId
        type: string
      - description: 'Data inicial para submissão da proposta. Formato aceito: YYYY-MM-DD'
        in: query
        name: startDate
        type: string
      - description: 'Data final para submissão da proposta. Formato aceito: YYYY-MM-DD'
        in: query
        name: endDate
        type: string
      - description: 'Tipo das matérias. Por padrão retorna todos os tipos. Valores
          permitidos: ''Proposição'', ''Boletim''.'
        in: query
        name: type
        type: string
      - description: Número da página. Por padrão é 1.
        in: query
        name: page
        type: integer
      - description: Quantidade de matérias retornadas por página. Por padrão é 15.
        in: query
        name: itemsPerPage
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Requisição bem sucedida
          schema:
            items:
              $ref: '#/definitions/response.SwaggerNewsPagination'
            type: array
        "400":
          description: Algum dado informado durante a requisição é inválido
          schema:
            $ref: '#/definitions/response.SwaggerError'
        "500":
          description: Ocorreu um erro inesperado durante o processamento da requisição
          schema:
            $ref: '#/definitions/response.SwaggerError'
      summary: Listagem das matérias mais recentes
      tags:
      - Matérias
  /news/newsletters/{newsletterId}:
    get:
      description: Esta requisição é responsável por retornar os detalhes do boletim
        pelo ID.
      operationId: GetNewsletterById
      parameters:
      - description: ID do boletim
        in: path
        name: newsletterId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Requisição bem sucedida
          schema:
            items:
              $ref: '#/definitions/response.SwaggerNewsletter'
            type: array
        "400":
          description: Algum dado informado durante a requisição é inválido
          schema:
            $ref: '#/definitions/response.SwaggerError'
        "500":
          description: Ocorreu um erro inesperado durante o processamento da requisição
          schema:
            $ref: '#/definitions/response.SwaggerError'
      summary: Busca dos detalhes do boletim pelo ID
      tags:
      - Boletins
  /news/propositions/{propositionId}:
    get:
      description: Esta requisição é responsável por retornar os detalhes da proposição
        pelo ID.
      operationId: GetPropositionById
      parameters:
      - description: ID da proposição
        in: path
        name: propositionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Requisição bem sucedida
          schema:
            items:
              $ref: '#/definitions/response.SwaggerProposition'
            type: array
        "400":
          description: Algum dado informado durante a requisição é inválido
          schema:
            $ref: '#/definitions/response.SwaggerError'
        "500":
          description: Ocorreu um erro inesperado durante o processamento da requisição
          schema:
            $ref: '#/definitions/response.SwaggerError'
      summary: Busca dos detalhes da proposição pelo ID
      tags:
      - Proposições
  /news/trending:
    get:
      description: Esta requisição é responsável por retornar as matérias mais populares
        disponíveis na plataforma Você na Câmara.
      operationId: GetTrending
      parameters:
      - description: Parte do conteúdo das matérias, no título ou conteúdo.
        in: query
        name: content
        type: string
      - description: ID do deputado que elaborou a proposição.
        in: query
        name: deputyId
        type: string
      - description: ID do partido que elaborou a proposição.
        in: query
        name: partyId
        type: string
      - description: ID da organização que elaborou a proposição.
        in: query
        name: organizationId
        type: string
      - description: 'Data inicial para submissão da proposta. Formato aceito: YYYY-MM-DD'
        in: query
        name: startDate
        type: string
      - description: 'Data final para submissão da proposta. Formato aceito: YYYY-MM-DD'
        in: query
        name: endDate
        type: string
      - description: 'Tipo das matérias. Por padrão retorna todos os tipos. Valores
          permitidos: ''Proposição'', ''Boletim''.'
        in: query
        name: type
        type: string
      - description: Número da página. Por padrão é 1.
        in: query
        name: page
        type: integer
      - description: Quantidade de matérias retornadas por página. Por padrão é 15.
        in: query
        name: itemsPerPage
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Requisição bem sucedida
          schema:
            items:
              $ref: '#/definitions/response.SwaggerNewsPagination'
            type: array
        "400":
          description: Algum dado informado durante a requisição é inválido
          schema:
            $ref: '#/definitions/response.SwaggerError'
        "500":
          description: Ocorreu um erro inesperado durante o processamento da requisição
          schema:
            $ref: '#/definitions/response.SwaggerError'
      summary: Listagem das matérias mais populares
      tags:
      - Matérias
  /resources:
    get:
      description: Esta requisição é responsável por retornar todos os recursos da
        plataforma.
      operationId: GetResources
      produces:
      - application/json
      responses:
        "200":
          description: Requisição bem sucedida
          schema:
            items:
              $ref: '#/definitions/response.SwaggerResources'
            type: array
        "500":
          description: Ocorreu um erro inesperado durante o processamento da requisição
          schema:
            $ref: '#/definitions/response.SwaggerError'
      summary: Busca de todos os recursos
      tags:
      - Recursos
swagger: "2.0"
