version: '3'

services:
  vnc_read_api:
    image: golang:alpine
    container_name: vnc_read_api
    restart: always
    working_dir: /app
    volumes:
      - ./src:/app
    command: sh -c "go build -o main main.go && ./main"
    ports:
      - "8084:8080"
    networks:
      - vnc_network

networks:
  vnc_network:
    external: true
