services:
    vnc_api:
        container_name: vnc_api
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src/config/.env:/config/.env
        restart: always
        ports:
            - "8083:8080"
        networks:
            - vnc_network

networks:
    vnc_network:
        external: true
